Granite_House/Areas/Admin/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Granite_House.Data;
using Granite_House.Models;
using Granite_House.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Granite_House.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class AdminUsersController : Controller
    {
        private readonly ApplicationDbContext _db;
        public AdminUsersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.ApplicationUsers.ToList());
        }

        //Get Edit
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || id.Trim().Length == 0)
                return NotFound();

            var userFromDb = await _db.ApplicationUsers.FindAsync(id);
            if (userFromDb == null)
                return NotFound();
            return View(userFromDb);
        }

        //Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
                return NotFound();
            if(ModelState.IsValid)
            {
                ApplicationUser userFromDb = _db.ApplicationUsers.Where(p => p.Id == id).FirstOrDefault();
                userFromDb.Name = applicationUser.Name;
                userFromDb.PhoneNumber = applicationUser.PhoneNumber;

                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(applicationUser);
        }

        //Get Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || id.Trim().Length == 0)
                return NotFound();

            var userFromDb = await _db.ApplicationUsers.FindAsync(id);
            if (userFromDb == null)
                return NotFound();
            return View(userFromDb);
        }

        //Post Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(string id)
        {
            ApplicationUser userFromDb = _db.ApplicationUsers.Where(p => p.Id == id).FirstOrDefault();
            userFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Granite_House/Areas/Admin/Controllers/ProductsController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Granite_House.Data;
using Granite_House.Models;
using Granite_House.Models.ViewModels;
using Granite_House.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Granite_House.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public ProductsViewModel ProductsVM { get; set; }

        private string dirSep;

        public ProductsController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
            dirSep = Path.DirectorySeparatorChar.ToString();
            ProductsVM = new ProductsViewModel()
            {
                ProductTypes = _db.ProductTypes.OrderBy(p=>p.Name).ToList(),
                SpecialTags = _db.SpecialTags.OrderBy(p => p.Name).ToList(),
                Products = new Products()
            };
        }

        public async Task<IActionResult> Index()
        {
            var products = _db.Products.Include(pt => pt.ProductTypes).Include(st => st.SpecialTags);
            return View(await products.ToListAsync());
        }

        //GET Products Create
        public IActionResult Create()
        {
            return View(ProductsVM);
        }

        //POST Products Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost()
        {
            if (!ModelState.IsValid)
                return View(ProductsVM);
            if (_db.Products.Count() > 0)
                ProductsVM.Products.Id = _db.Products.Max(p => p.Id) + 1;
            else
                ProductsVM.Products.Id = 1;
            _db.Products.Add(ProductsVM.Products);
            await _db.SaveChangesAsync();
            Products productsFromDb = _db.Products.Find(ProductsVM.Products.Id);

            //Image being saved
            string webRootPath = _hostingEnvironment.WebRootPath;
            IFormFileCollection files = HttpContext.Request.Form.Files;
            if (files.Count!=0)
            {
                //files has been uploaded
                string uploads = webRootPath + dirSep + SD.ImageFolder;
                string extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(uploads + dirSep + ProductsVM.Products.Id + extension, FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                productsFromDb.Image = dirSep + SD.ImageFolder + dirSep + ProductsVM.Products.Id + extension;
            }
            else
            {
                //when user doesn't upload image
                string uploads = webRootPath + dirSep + SD.ImageFolder+ dirSep + SD.DefaultProductImage;
                System.IO.File.Copy(uploads, webRootPath + dirSep + SD.ImageFolder + dirSep + ProductsVM.Products.Id + ".jpg");
                productsFromDb.Image = dirSep + SD.ImageFolder + dirSep + ProductsVM.Products.Id + ".jpg";
            }
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //GET Products Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);
            if (ProductsVM.Products == null)
                return NotFound();

            return View(ProductsVM);
        }

        //POST Products Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if(ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                IFormFileCollection files = HttpContext.Request.Form.Files;

                Products productFromDb = _db.Products.Where(p => p.Id == ProductsVM.Products.Id).FirstOrDefault();

                if(files != null && files.Count>0 && files[0] != null && files[0].Length>0)
                {
                    //if user uploads a new image
                    string uploads = webRootPath + dirSep + SD.ImageFolder;
                    var extension_new = Path.GetExtension(files[0].FileName);
                    var extension_old = Path.GetExtension(productFromDb.Image);

                    if (System.IO.File.Exists(uploads + dirSep + ProductsVM.Products.Id + extension_old))
                        System.IO.File.Delete(uploads + dirSep + ProductsVM.Products.Id + extension_old);

                    using (var fileStream = new FileStream(uploads + dirSep + ProductsVM.Products.Id + extension_new, FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    ProductsVM.Products.Image = dirSep + SD.ImageFolder + dirSep + ProductsVM.Products.Id + extension_new;
                }

                productFromDb.Name = ProductsVM.Products.Name;
                productFromDb.Price = ProductsVM.Products.Price;
                productFromDb.Available = ProductsVM.Products.Available;
                productFromDb.ProductTypeId = ProductsVM.Products.ProductTypeId;
                productFromDb.SpecialTagsId = ProductsVM.Products.SpecialTagsId;
                productFromDb.ShadeColor = ProductsVM.Products.ShadeColor;
                if (ProductsVM.Products.Image != null)
                    productFromDb.Image = ProductsVM.Products.Image;
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(ProductsVM);
        }

        //GET Products Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);
            if (ProductsVM.Products == null)
                return NotFound();

            return View(ProductsVM);
        }

        //GET Products Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);
            if (ProductsVM.Products == null)
                return NotFound();

            return View(ProductsVM);
        }

        //POST Products Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string webRootPath = _hostingEnvironment.WebRootPath;
            Products products =  await _db.Products.FindAsync(id);
            if (products == null)
                return NotFound();

            string uploads = Path.Combine(webRootPath, SD.ImageFolder);
            string extension = Path.GetExtension(products.Image);
            if (System.IO.File.Exists(Path.Combine(uploads, products.Id + extension)))
                System.IO.File.Delete(Path.Combine(uploads, products.Id + extension));

            _db.Products.Remove(products);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Granite_House/Areas/Admin/Controllers/SpecialTagsController.cs
using System.Linq;
using System.Threading.Tasks;
using Granite_House.Data;
using Granite_House.Models;
using Granite_House.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Granite_House.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class SpecialTagsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SpecialTagsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.SpecialTags.ToList());
        }

        //GET Create Action Method
        public IActionResult Create()
        {
            return View();
        }

        //POST Create Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                if (_db.SpecialTags.Count() > 0)
                    specialTags.Id = _db.SpecialTags.Max(p => p.Id) + 1;
                else
                    specialTags.Id = 1;
                _db.Add(specialTags);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(specialTags);
        }

        //GET Edit Action Method
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();
            SpecialTags specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
                return NotFound();
            return View(specialTag);
        }

        //POST Edit Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SpecialTags specialTag)
        {
            if (id != specialTag.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _db.Update(specialTag);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(specialTag);
        }

        //GET Details Action Method
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();
            SpecialTags specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
                return NotFound();
            return View(specialTag);
        }

        //GET Delete Action Method
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            SpecialTags specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
                return NotFound();
            return View(specialTag);
        }

        //POST Delete Action Method
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            SpecialTags specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
                return NotFound();
            _db.SpecialTags.Remove(specialTag);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Granite_House/Views/Shared/_AppointmentCustormerDetails.cshtml
@model Granite_House.Models.Appointments

<h4 class="text-success">Appointment Details</h4>

<div style="height:100%; background-color:aliceblue;" class="container border">
    <div class="col-12">
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Full Name
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerName" readonly class="form-control" />
            </div>
            <div class="col-2">

            </div>
            <div class="col-2">
                Email
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerEmail" readonly class="form-control" />
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Phone Number
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerPhoneNumber" readonly class="form-control" />
            </div>
            <div class="col-2">

            </div>
            <div class="col-2">
                Appointment Date
            </div>
            <div class="col-3">
                <input asp-for="@Model.AppointmentDate" readonly class="form-control" />
            </div>
        </div>
    </div>

</div>

Granite_House/Views/Shared/_AppointmentProductDetails.cshtml
@model List<Granite_House.Models.Products>
@if (Model.Count > 0)
{
<table class="table table-striped" width="100%">
    <tr class="table-info">
        <th style="text-align:center; width:20%"></th>
        <th style="text-align:center; width:20%">
            <label asp-for="@Model.FirstOrDefault().Name"></label>
        </th>
        <th style="text-align:center; width:20%">
            <label asp-for="@Model.FirstOrDefault().Price"></label>
        </th>
        <th style="text-align:center; width:20%">
            <label asp-for="@Model.FirstOrDefault().ShadeColor"></label>
        </th>
        <th style="text-align:center; width:20%">
            <label asp-for="@Model.FirstOrDefault().ProductTypes.Name"></label>
        </th>
        <th style="text-align:center;"></th>
    </tr>
    @foreach (Products item in Model)
    {
        <tr style="padding:50px;">
            <td>
                <a asp-area="Customer" asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">
                    <img src="@item.Image" width="100%" style="margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9;" />
                </a>
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(c => item.Name)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(c => item.Price)
            </td>

            <td style="text-align:center">
                @Html.DisplayFor(c => item.ShadeColor)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(c => item.ProductTypes.Name)
            </td>
        </tr>
    }
</table>
}
else
{
    <div>No items added to the shopping cart...</div>
}

Granite_House/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Granite_House.Extensions
@using Granite_House.Utility

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Granite_House</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </environment>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Granite House</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a></li>
                @if (User.IsInRole(SD.SuperAdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Special Tags</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">Admin Users</a></li>
                }
                @if (User.IsInRole(SD.SuperAdminEndUser) || User.IsInRole(SD.AdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Appointments" asp-action="Index">Appointments</a></li>
                }
                    @if (HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart") != null)
                    {
                        <li style="color:white">
                            <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp;
                                @{
                                    int count = HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart").Count;
                                }
                                (@count)
                            </a>
                        </li>
                    }
                    else
                    {
                        <li style="color:white">
                            <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp;

                                (0)

                            </a>
                        </li>
                    }
                </ul>
        </div>
        <div>
            <partial name="_LoginPartial" />
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <footer>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-bottom">
                <p style="color:ghostwhite;">&copy; 2018 - Granite House (fantics.cloud)</p>
            </nav>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
      </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Granite_House/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px;">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" title="Edit" href="@Url.Action("Edit", new { Id = Model } )">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" title="Details" href="@Url.Action("Details", new { Id = Model })">
            <i class="fas fa-list-ul"></i>
        </a>
        <a type="button" class="btn btn-danger" title="Delete" href="@Url.Action("Delete", new { Id = Model })">
            <i class="far fa-trash-alt"></i>
        </a>
    </div>
</td>